language: ruby
sudo: false
cache: bundler
rvm:
- 2.2
script: make
deploy:
- provider: s3
  access_key_id: AKIAIA5ECJTPIGFZOPXA
  secret_access_key:
    secure: fqe2kx2WrAd1HqVqxyQxqI1bQnUWpN1HldPCuzGNrs7HAOl1CR3s5odscHa2btNsM1kAMszbwd3nLoUXgTd+HaL7D6i6qNdxl3wdcdKj6P4Csmg7RNVpGw/KghLMgz++9ED8OEKoIA/gfWB2IcPcrvzOB452qYRElNzbF24GXpc=
  bucket: justincampbell.me
  local-dir: build
  skip_cleanup: true
  on:
    branch: master
