baseURL: "https://justincampbell.me"
languageCode: "en-us"
title: "Justin Campbell"

params:
  github_url: "https://github.com/justincampbell"
  schedule_url: "https://cal.com/justincampbell/meet"
  source_url: "https://github.com/justincampbell/justincampbell.me"

markup:
  goldmark:
    renderer:
      unsafe: true
